<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductFinalSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            // Catégorie 1 : Électronique (id = 1)
            [
                'name' => 'Smartphone Galaxy X10',
                'price' => 5_160_000,
                'old_price' => 6_010_000,
                'discount_percentage' => 15,
                'description' => 'Un smartphone puissant avec écran AMOLED et triple caméra.',
                'short_description' => 'Smartphone haut de gamme',
                'rating' => 4.5,
                'review_count' => 120,
                'image' => 'galaxyx10.jpg',
                'slug' => 'smartphone-galaxy-x10',
                'sku' => 'ELEC-001',
                'weight' => 0.45,
                'dimensions' => '15x7x0.8 cm',
                'brand' => 'Samsung',
                'stock_quantity' => 50,
                'in_stock' => 1,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Galaxy X10',
                'meta_description' => 'Smartphone Galaxy X10 avec écran AMOLED.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'name' => 'Casque Bluetooth Pro',
                'price' => 774_000,
                'old_price' => 1_120_000,
                'discount_percentage' => 30,
                'description' => 'Casque sans fil avec réduction de bruit active.',
                'short_description' => 'Casque audio sans fil',
                'rating' => 4.7,
                'review_count' => 85,
                'image' => 'casquepro.jpg',
                'slug' => 'casque-bluetooth-pro',
                'sku' => 'ELEC-002',
                'weight' => 0.25,
                'dimensions' => '18x15x8 cm',
                'brand' => 'Sony',
                'stock_quantity' => 80,
                'in_stock' => 1,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Casque Bluetooth Pro',
                'meta_description' => 'Casque sans fil haute qualité Sony.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'name' => 'Laptop Ultrabook Air',
                'price' => 8_600_000,
                'old_price' => 10_300_000,
                'discount_percentage' => 20,
                'description' => 'Ordinateur portable léger et puissant pour le travail.',
                'short_description' => 'Laptop 13 pouces',
                'rating' => 4.6,
                'review_count' => 65,
                'image' => 'ultrabookair.jpg',
                'slug' => 'laptop-ultrabook-air',
                'sku' => 'ELEC-003',
                'weight' => 1.20,
                'dimensions' => '30x21x1.5 cm',
                'brand' => 'Dell',
                'stock_quantity' => 30,
                'in_stock' => 1,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Ultrabook Air',
                'meta_description' => 'Laptop puissant et léger.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'name' => 'Montre Connectée FitX',
                'price' => 1_290_000,
                'old_price' => 1_720_000,
                'discount_percentage' => 25,
                'description' => 'Montre intelligente avec suivi sportif et santé.',
                'short_description' => 'Montre connectée fitness',
                'rating' => 4.3,
                'review_count' => 200,
                'image' => 'fitxwatch.jpg',
                'slug' => 'montre-connectee-fitx',
                'sku' => 'ELEC-004',
                'weight' => 0.08,
                'dimensions' => '4x4x1 cm',
                'brand' => 'Fitbit',
                'stock_quantity' => 100,
                'in_stock' => 1,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'FitX Smartwatch',
                'meta_description' => 'Montre connectée pour sport et santé.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],
            [
                'name' => 'Tablette Tab Pro 11',
                'price' => 3_440_000,
                'old_price' => 4_300_000,
                'discount_percentage' => 20,
                'description' => 'Tablette tactile avec stylet et écran haute résolution.',
                'short_description' => 'Tablette 11 pouces',
                'rating' => 4.4,
                'review_count' => 90,
                'image' => 'tabpro11.jpg',
                'slug' => 'tablette-tab-pro-11',
                'sku' => 'ELEC-005',
                'weight' => 0.65,
                'dimensions' => '25x16x0.7 cm',
                'brand' => 'Apple',
                'stock_quantity' => 40,
                'in_stock' => 1,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Tab Pro 11',
                'meta_description' => 'Tablette performante avec stylet.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
            ],

            // Catégorie 2 : Mode (id = 2)
            [
                'name' => 'Chaussures de sport AirMax',
                'price' => 1_117_000,
                'old_price' => 1_374_000,
                'discount_percentage' => 18,
                'description' => 'Baskets confortables pour sport et style.',
                'short_description' => 'Baskets AirMax',
                'rating' => 4.8,
                'review_count' => 150,
                'image' => 'airmax.jpg',
                'slug' => 'chaussures-airmax',
                'sku' => 'MODE-001',
                'weight' => 0.85,
                'dimensions' => '30x20x12 cm',
                'brand' => 'Nike',
                'stock_quantity' => 70,
                'in_stock' => 1,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'AirMax chaussures',
                'meta_description' => 'Chaussures de sport tendance.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
            ],
            [
                'name' => 'Sac à main cuir Élégance',
                'price' => 1_722_000,
                'old_price' => 2_150_000,
                'discount_percentage' => 20,
                'description' => 'Sac en cuir véritable avec finition haut de gamme.',
                'short_description' => 'Sac à main en cuir',
                'rating' => 4.6,
                'review_count' => 95,
                'image' => 'sacelegance.jpg',
                'slug' => 'sac-main-cuir-elegance',
                'sku' => 'MODE-002',
                'weight' => 1.20,
                'dimensions' => '40x30x15 cm',
                'brand' => 'Gucci',
                'stock_quantity' => 25,
                'in_stock' => 1,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Sac Élégance',
                'meta_description' => 'Sac à main en cuir véritable.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
            ],
            [
                'name' => 'Veste en jean classique',
                'price' => 686_000,
                'old_price' => 857_000,
                'discount_percentage' => 20,
                'description' => 'Veste en jean bleu, style intemporel.',
                'short_description' => 'Veste denim classique',
                'rating' => 4.4,
                'review_count' => 65,
                'image' => 'vestedenim.jpg',
                'slug' => 'veste-en-jean-classique',
                'sku' => 'MODE-003',
                'weight' => 1.10,
                'dimensions' => '60x40x5 cm',
                'brand' => 'Levis',
                'stock_quantity' => 60,
                'in_stock' => 1,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Veste Jean',
                'meta_description' => 'Veste en jean tendance.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
            ],
            [
                'name' => 'Montre analogique chic',
                'price' => 1_290_000,
                'old_price' => 1_720_000,
                'discount_percentage' => 25,
                'description' => 'Montre élégante avec bracelet en cuir.',
                'short_description' => 'Montre pour homme/femme',
                'rating' => 4.5,
                'review_count' => 80,
                'image' => 'montrechic.jpg',
                'slug' => 'montre-analogique-chic',
                'sku' => 'MODE-004',
                'weight' => 0.10,
                'dimensions' => '5x5x0.8 cm',
                'brand' => 'Rolex',
                'stock_quantity' => 40,
                'in_stock' => 1,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Montre Chic',
                'meta_description' => 'Montre analogique en cuir.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
            ],
            [
                'name' => 'T-shirt coton premium',
                'price' => 215_000,
                'old_price' => 247_000,
                'discount_percentage' => 15,
                'description' => 'T-shirt en coton bio ultra-confortable.',
                'short_description' => 'T-shirt coton bio',
                'rating' => 4.2,
                'review_count' => 55,
                'image' => 'tshirtpremium.jpg',
                'slug' => 't-shirt-coton-premium',
                'sku' => 'MODE-005',
                'weight' => 0.30,
                'dimensions' => '40x30x1 cm',
                'brand' => 'Zara',
                'stock_quantity' => 100,
                'in_stock' => 1,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'T-shirt Premium',
                'meta_description' => 'T-shirt coton bio.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
            ],

            // Catégorie 3 : Maison & Décoration (id = 3)
            [
                'name' => 'Canapé d’angle moderne',
                'price' => 12_880_000,
                'old_price' => 15_450_000,
                'discount_percentage' => 15,
                'description' => 'Canapé confortable en tissu gris.',
                'short_description' => 'Canapé 4 places',
                'rating' => 4.6,
                'review_count' => 50,
                'image' => 'canapeangle.jpg',
                'slug' => 'canape-angle-moderne',
                'sku' => 'MAIS-001',
                'weight' => 35.00,
                'dimensions' => '250x150x90 cm',
                'brand' => 'Ikea',
                'stock_quantity' => 20,
                'in_stock' => 1,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Canapé Angle',
                'meta_description' => 'Canapé d’angle moderne et confortable.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
            ],
            [
                'name' => 'Table à manger en bois',
                'price' => 8_600_000,
                'old_price' => 10_300_000,
                'discount_percentage' => 20,
                'description' => 'Table en bois massif pour 6 personnes.',
                'short_description' => 'Table bois 6 personnes',
                'rating' => 4.5,
                'review_count' => 40,
                'image' => 'tablebois.jpg',
                'slug' => 'table-manger-bois',
                'sku' => 'MAIS-002',
                'weight' => 25.00,
                'dimensions' => '180x90x75 cm',
                'brand' => 'Ikea',
                'stock_quantity' => 15,
                'in_stock' => 1,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Table Bois',
                'meta_description' => 'Table en bois massif.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
            ],
            [
                'name' => 'Chaise ergonomique de bureau',
                'price' => 2_150_000,
                'old_price' => 2_580_000,
                'discount_percentage' => 15,
                'description' => 'Chaise de bureau avec soutien lombaire.',
                'short_description' => 'Chaise de bureau ergonomique',
                'rating' => 4.3,
                'review_count' => 60,
                'image' => 'chaisebureau.jpg',
                'slug' => 'chaise-ergonomique-bureau',
                'sku' => 'MAIS-003',
                'weight' => 12.00,
                'dimensions' => '70x70x120 cm',
                'brand' => 'Ikea',
                'stock_quantity' => 35,
                'in_stock' => 1,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Chaise Bureau',
                'meta_description' => 'Chaise ergonomique confortable.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
            ],
            [
                'name' => 'Lampe sur pied LED',
                'price' => 774_000,
                'old_price' => 1_030_000,
                'discount_percentage' => 25,
                'description' => 'Lampe LED avec intensité réglable.',
                'short_description' => 'Lampe LED moderne',
                'rating' => 4.4,
                'review_count' => 30,
                'image' => 'lampeled.jpg',
                'slug' => 'lampe-sur-pied-led',
                'sku' => 'MAIS-004',
                'weight' => 5.00,
                'dimensions' => '40x40x160 cm',
                'brand' => 'Philips',
                'stock_quantity' => 60,
                'in_stock' => 1,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Lampe LED',
                'meta_description' => 'Lampe sur pied LED moderne.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
            ],
            [
                'name' => 'Tapis salon doux',
                'price' => 1_290_000,
                'old_price' => 1_720_000,
                'discount_percentage' => 25,
                'description' => 'Tapis moelleux pour salon, facile à nettoyer.',
                'short_description' => 'Tapis salon moderne',
                'rating' => 4.2,
                'review_count' => 25,
                'image' => 'tapissalon.jpg',
                'slug' => 'tapis-salon-doux',
                'sku' => 'MAIS-005',
                'weight' => 8.00,
                'dimensions' => '200x150 cm',
                'brand' => 'Ikea',
                'stock_quantity' => 45,
                'in_stock' => 1,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Tapis Salon',
                'meta_description' => 'Tapis moelleux pour salon.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
            ],

            // Catégorie 4 : Sports & Loisirs (id = 4)
            [
                'name' => 'Vélo de montagne Xtreme',
                'price' => 4_300_000,
                'old_price' => 5_160_000,
                'discount_percentage' => 15,
                'description' => 'Vélo robuste pour tout terrain.',
                'short_description' => 'Vélo montagne',
                'rating' => 4.7,
                'review_count' => 75,
                'image' => 'velomountain.jpg',
                'slug' => 'velo-montagne-xtreme',
                'sku' => 'SPORT-001',
                'weight' => 15.00,
                'dimensions' => '180x60x100 cm',
                'brand' => 'Trek',
                'stock_quantity' => 30,
                'in_stock' => 1,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Vélo Montagne',
                'meta_description' => 'Vélo robuste pour tout terrain.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'name' => 'Tapis de yoga premium',
                'price' => 430_000,
                'old_price' => 515_000,
                'discount_percentage' => 15,
                'description' => 'Tapis antidérapant pour yoga et pilates.',
                'short_description' => 'Tapis yoga confortable',
                'rating' => 4.5,
                'review_count' => 40,
                'image' => 'tapisyoga.jpg',
                'slug' => 'tapis-yoga-premium',
                'sku' => 'SPORT-002',
                'weight' => 1.50,
                'dimensions' => '180x60x0.5 cm',
                'brand' => 'Nike',
                'stock_quantity' => 60,
                'in_stock' => 1,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Tapis Yoga',
                'meta_description' => 'Tapis yoga confortable et antidérapant.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'name' => 'Ballon de football officiel',
                'price' => 215_000,
                'old_price' => 258_000,
                'discount_percentage' => 15,
                'description' => 'Ballon de football homologué pour matchs officiels.',
                'short_description' => 'Ballon football',
                'rating' => 4.6,
                'review_count' => 85,
                'image' => 'ballonfoot.jpg',
                'slug' => 'ballon-football-officiel',
                'sku' => 'SPORT-003',
                'weight' => 0.45,
                'dimensions' => '22x22x22 cm',
                'brand' => 'Adidas',
                'stock_quantity' => 100,
                'in_stock' => 1,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Ballon Football',
                'meta_description' => 'Ballon de football officiel.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'name' => 'Raquette de tennis Pro',
                'price' => 1_290_000,
                'old_price' => 1_720_000,
                'discount_percentage' => 25,
                'description' => 'Raquette légère et résistante pour joueurs avancés.',
                'short_description' => 'Raquette tennis',
                'rating' => 4.5,
                'review_count' => 60,
                'image' => 'raquettetennis.jpg',
                'slug' => 'raquette-tennis-pro',
                'sku' => 'SPORT-004',
                'weight' => 0.35,
                'dimensions' => '70x25x5 cm',
                'brand' => 'Wilson',
                'stock_quantity' => 50,
                'in_stock' => 1,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Raquette Tennis',
                'meta_description' => 'Raquette de tennis professionnelle.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
            [
                'name' => 'Haltères réglables 10-50kg',
                'price' => 2_580_000,
                'old_price' => 3_010_000,
                'discount_percentage' => 15,
                'description' => 'Haltères pour musculation à domicile.',
                'short_description' => 'Haltères gym',
                'rating' => 4.4,
                'review_count' => 45,
                'image' => 'halteres.jpg',
                'slug' => 'halteres-reglables-10-50kg',
                'sku' => 'SPORT-005',
                'weight' => 20.00,
                'dimensions' => '50x20x20 cm',
                'brand' => 'Decathlon',
                'stock_quantity' => 30,
                'in_stock' => 1,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Haltères Réglables',
                'meta_description' => 'Haltères pour musculation à domicile.',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
            ],
        ]);
    }
}
